extends: default

rules:
  line-length:
    max: 120 # допустимая длина строки
    level: warning # не ошибка, а предупреждение
  document-start:
    present: false # не требовать `---` в начале
  trailing-spaces:
    level: error # пробелы в конце — ошибка
  new-line-at-end-of-file:
    level: warning # мягкая рекомендация
  braces: disable
