global:
  tlsDisable: false

server:
  image:
    repository: hashicorp/vault
    tag: "1.15.6"

  logLevel: info

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true

  dataStorage:
    enabled: true
    size: 20Gi
    storageClass: standard
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: standard
    accessMode: ReadWriteOnce

  serviceAccount:
    create: false
    name: vault

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

ui:
  enabled: true

injector:
  enabled: true
  replicas: 2