apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: backend-secrets
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/apps/database
        property: db_user

    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/apps/database
        property: db_password