apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-example
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent-demo
  template:
    metadata:
      labels:
        app: vault-agent-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "backend-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/apps/database"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/data/apps/database" -}}
          DB_USER={{ .Data.data.db_user }}
          DB_PASSWORD={{ .Data.data.db_password }}
          {{- end }}
    spec:
      serviceAccountName: backend
      containers:
        - name: app
          image: alpine
          command: ["sleep","3600"]