apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
  namespace: vault
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: vault-backup

        spec:
          serviceAccountName: vault
          restartPolicy: OnFailure

          containers:
          - name: vault-backup
            image: hashicorp/vault:1.15.6

            env:
            - name: VAULT_ADDR
              value: https://vault.vault.svc:8200

            command:
            - /bin/sh
            - -c
            - |
              mkdir -p /backup
              vault operator raft snapshot save /backup/vault-$(date +%s).snap

            volumeMounts:
            - name: backup
              mountPath: /backup

          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: vault-backup