apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vault-alerts
  namespace: monitoring
spec:
  groups:
    - name: vault.rules
      rules:

        - alert: VaultDown
          expr: up{job="vault"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Vault instance is down"

        - alert: VaultHighLatency
          expr: vault_core_handle_request{quantile="0.99"} > 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Vault request latency is high"

        - alert: VaultSealed
          expr: vault_core_unsealed == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Vault is sealed"