rollout:
  strategy: canary
  steps:
    - setWeight: 10
    - pause: {duration: 60}
    - setWeight: 30
    - pause: {duration: 60}
    - setWeight: 60
    - pause: {duration: 60}
    - setWeight: 100
